name: jaspr_shared_value
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
topic: jaspr

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  collection: ^1.19.0
  jaspr: ">=0.16.1 <2.0.0"  
  web: ^1.0.0

dev_dependencies:
  jaspr_test: ">=0.16.1 <2.0.0"  
  lints: ^4.0.0
  test: ^1.24.0
